### ISSUE TITLE
plugin is not implemented on ios

### ISSUE THREAD

**Issue by muuvmuuv** [migtam628/capacitor-ios-app-tracking#14]
I am getting the error "plugin is not implemented on iOS" with latest Xcode and Capacitor. I installed the plugin and ran `cap sync ios`. It looks also a bit weird how the plugin is implemented. It looks like its never initiated.

**Comment by migtam628** [comment]
I've had users had the same problem but I've tested as shown in #13 and it works fine for me. I'm not sure what's the issue. I'll take a look at this. I'll update it as soon as i fixe it.

**Comment by muuvmuuv** [comment]
I just wrote one myself for Capacitor
