### ISSUE TITLE
Support for Capacitor 2.x

### ISSUE THREAD

**Issue by BenjaminDish** [migtam628/capacitor-ios-app-tracking#15]
Hello, 

Since the upgrade to Capacitor 3, it seems the plugin doesn't work with previous releases of Capacitor as the plugin requires Capacitor 3 as peer dependency. I'm currently having apps in production using Capacitor 2.1.0 without the ability to upgrade them to Capacitor 3. I now need to implement the new App Tracking Transparency from Apple.

Would it be possible to restore Capacitor 2 compatibility ?

Thanks

**Comment by migtam628** [comment]
Hello @BenjaminDish
just uninstall `npm uninstall -S capacitor-ios-app-tracking` and install version 1.0.2 `npm i -S capacitor-ios-app-tracking@1.0.2`
