### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by FerBastiaens** [migtam628/capacitor-ios-app-tracking#18]
Hi,

Thanks for this package. I am using it in an Ionic Capacitor project.
I recently tried to upgrade from capacitor 2.x.x. to capacitor 3.x.x. Therefore I updated this package to version 1.0.3.

This package stopped working now. When opening the capacitor project in xcode, it shows the following error:

![image](https://user-images.githubusercontent.com/15211564/150152698-47f93e60-6cbe-4d01-a01a-5c434fbb3745.png)

When I adjust the conditions back to 
` if #available(iOS 14.0, *)`
the package works again as expected.

iOS 15.0 should not be added to this condition, because the wildcard ('*') already checks for any version above the iOS 14.0.

Thanks and regards,
Fer

**Comment by raycarter** [comment]
same issue. @migtam628 could you fix this as @FerBastiaens suggested? Thanks!

**Comment by migtam628** [comment]
Sorry about that. I merged the PR should be working now.. I will update the npm package now. thanks
