### ISSUE TITLE
Release updated package to npm

### ISSUE THREAD

**Issue by gabceb** [migtam628/capacitor-ios-app-tracking#5]
Hi @migtam628. Huge thanks for the package. Would it be possible to publish the newer code into npm. Having issues with the Android build that was fixed on #1 

Thanks in advance!

**Comment by pelupotter** [comment]
Hi, same here!

**Comment by VincenzoAsciolla** [comment]
Hi @migtam628 thanks for this package, but we all are having problems with the Android build.

It seems that the fix [#1](https://github.com/migtam628/capacitor-ios-app-tracking/issues/1) hasn't been merged correctly.

Could you please merge the fix so that all developers can use your package with some tricks :)

Thanks in advance

**Comment by ciesielskico** [comment]
I could really use this

**Comment by ivansoldoid90t** [comment]
Hi @migtam628. thanks for the package. Can you release a new tag since it doesn't contain the android issue fix?

**Comment by non3x** [comment]
Hello, my android builds are also failing :( @migtam628 please release the bugfix on npm

**Comment by migtam628** [comment]
Hey guys sorry for the delay on the update. I've been busy with family matters. I'll be happy to review the code and Ill upload it to npm. and Thanks for the support.  @gabceb  @pelupotter @VincenzoAsciolla @ciesielskico  @ivansoldoid90t @non3x ..

**Comment by gabceb** [comment]
Totally understandable @migtam628. Let us know if we can help. Just today I started moving over to https://github.com/ottimis/capacitor3-ios-app-tracking which now has Cap 3 support. Maybe we can get @ottimis to open a PR against this repo and pick that up

**Comment by migtam628** [comment]
@gabceb Thank you man. I appreciate it. I was working on it las night. I updated the repo and npm package. let me know if it's working properly.
