### ISSUE TITLE
Need to have an Android version that returns true

### ISSUE THREAD

**Issue by brian-g** [migtam628/capacitor-ios-app-tracking#6]
Our app is cross-platform and we would need to have the Android portion of the plugin implemented so we can have a single project.

**Comment by albertogallego** [comment]
Hi @brian-g! How did you solve this issue? I'm in the same situation as you.

Thanks in advance!

**Comment by brian-g** [comment]
We patched the package.json to remove the Android references. The patch is applied automatically by yarn in a post install script.

**Comment by dmastag** [comment]
@brian-g would you mind sharing in detail how you did that ?

**Comment by brian-g** [comment]
Here is our patch file. We put this in a folder off of the root of the project called `patches`. We have the developer packages called `patch-package` and `postinstall-postinstall` installed in our package.json. In the "scripts" section of the package.json, we have "postinstall": "patch-package".

Hope this helps. 

[capacitor-ios-app-tracking+0.1.1.patch.zip](https://github.com/migtam628/capacitor-ios-app-tracking/files/6421828/capacitor-ios-app-tracking%2B0.1.1.patch.zip)
