### ISSUE TITLE
requestPermission resolves immediately with "unrequested"

### ISSUE THREAD

**Issue by JensUweB** [migtam628/capacitor-ios-app-tracking#8]
Hello there! 
I have a problem with an Ionic 5 Angular App. 

**Problem:**
Every time when I request the permission, the promise resolves immediately and returns "unrequested"

**Expected Behavior:**
Only resolve if the user has taken action and return the correct status.

This is a stripped down version of my implementation (in typescript):
``` ts
import { Response } from 'capacitor-ios-app-tracking';
const { Device, IOSAppTracking } = Plugins;

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent implements AfterViewInit {
// ... code here
 constructor(private platform: Platform) {
  this.platform.ready().then({
    // Platform is ready. Do stuff!
      this.getTrackingPermission().then(res => {
         // User has allowed tracking.
        // res.status is always "unrequested" here
     }).catch(err => {
        // User has denied tracking.
    });
  });
}
  /**
   * Requests tracking permission
   */
  getTrackingPermission(): Promise<Response> {
    return new Promise((resolve, reject) => {
      IOSAppTracking.getTrackingStatus().then((res: Response) => {
        console.log('Tracking Status: ' + res.status);
        if (res.status === 'unrequested') {
          IOSAppTracking.requestPermission().then((response: Response) => {
            console.log('Tracking Status: ' + response.status);
            resolve(response);
          });
        }
        if (res.status === 'authorized' || res.status === 'restricted') { resolve(res); }
        if (res.status === 'denied') { reject('Tracking permission denied'); }
      });
    });
  }
// ... more code
}
```

Am I missing something? 
Thanks for this plugin, btw. We really need this for our customer apps.

**Comment by jimmylewis1** [comment]
> Hello there!
> I have a problem with an Ionic 5 Angular App.
> 
> **Problem:**
> Every time when I request the permission, the promise resolves immediately and returns "unrequested"
> 
> **Expected Behavior:**
> Only resolve if the user has taken action and return the correct status.
> 
> This is a stripped down version of my implementation (in typescript):
> 
> ```ts
> import { Response } from 'capacitor-ios-app-tracking';
> const { Device, IOSAppTracking } = Plugins;
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: 'app.component.html',
>   styleUrls: ['app.component.scss']
> })
> export class AppComponent implements AfterViewInit {
> // ... code here
>  constructor(private platform: Platform) {
>   this.platform.ready().then({
>     // Platform is ready. Do stuff!
>       this.getTrackingPermission().then(res => {
>          // User has allowed tracking.
>         // res.status is always "unrequested" here
>      }).catch(err => {
>         // User has denied tracking.
>     });
>   });
> }
>   /**
>    * Requests tracking permission
>    */
>   getTrackingPermission(): Promise<Response> {
>     return new Promise((resolve, reject) => {
>       IOSAppTracking.getTrackingStatus().then((res: Response) => {
>         console.log('Tracking Status: ' + res.status);
>         if (res.status === 'unrequested') {
>           IOSAppTracking.requestPermission().then((response: Response) => {
>             console.log('Tracking Status: ' + response.status);
>             resolve(response);
>           });
>         }
>         if (res.status === 'authorized' || res.status === 'restricted') { resolve(res); }
>         if (res.status === 'denied') { reject('Tracking permission denied'); }
>       });
>     });
>   }
> // ... more code
> }
> ```
> 
> Am I missing something?
> Thanks for this plugin, btw. We really need this for our customer apps.

I'm experiencing the same thing. Also, getting a typescript error for the `requestPermission()` method indicating that I'm missing an argument that needs to be an object `{value: string}`. I noticed you weren't passing an argument in your method call, and the example given in the docs doesn't have an argument either.

**Comment by migtam628** [comment]
Hey guys.. So sorry for the delay. I've been busy with family matters. I'm back. any updates?. I'll review the code and update it. Thanks again guys
